import { ARMS, ARM_LABELS, PAIRS } from './workout-model.js';
import { METHODS, ROLES, WAVE } from './progression-presets.js';
import { keyPair, pairKey, progress, currentSlot, waveSuggestion, nextPair } from './progression-model.js';
export const esc = v => String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const options = (selected, allowed=PAIRS.map(keyPair)) => PAIRS.filter(p=>allowed.includes(keyPair(p))).map(p=>`<option value="${keyPair(p)}" ${selected===keyPair(p)?'selected':''}>${p.kg.toFixed(1)} кг · ${p.i}/${p.j}</option>`).join('');
export const button=(action,label,extra='',primary=false)=>`<button type="button" class="button ${primary?'button--primary':'button--quiet'}" data-prog="${action}" ${extra}>${label}</button>`;
const statuses={draft:'Черновик',active:'Активна',paused:'На паузе',completed:'Завершена',archived:'Архив',planned:'Запланировано',partial:'Частично',modified:'Завершено с изменениями',skipped:'Пропущено',replaced:'Заменено'};
export const status=v=>statuses[v]||v;
export function setsView(rows) {
  if(!rows.length)return '<p class="muted">Нет назначений</p>';
  const groups=[];
  for(const s of rows){const last=groups.at(-1);if(last&&last.i===s.i&&last.j===s.j&&last.reps===s.reps&&last.role===s.role&&last.repMax===s.repMax)last.count++;else groups.push({...s,count:1});}
  return groups.map(s=>`<div class="prog-set"><span>${ROLES[s.role]||'Подход'}${s.count>1?` · ${s.count} подхода`:''}</span><strong>${s.kg.toFixed(1)} кг × ${s.maxTest?'максимум':s.repMax?`${s.reps}–${s.repMax}`:s.reps}</strong><small>Пружины ${s.i} / ${s.j} · отдых ${s.restSec??0} с</small></div>`).join('');
}
export function slotView(slot, details=false) {
  return `<article class="prog-slot ${slot.closed?'is-closed':''}" id="slot-${esc(slot.id)}"><div class="prog-line"><h3>Неделя ${slot.week} · ${slot.index%2?'Б':'А'}</h3><span class="count-pill">${status(slot.status)}</span></div><p class="muted">${esc(slot.date)}${slot.preliminary?' · Предварительно: зависит от выполнения':''}</p>
    <div class="prog-arms">${ARMS.filter(a=>slot.arms[a]).map(a=>`<div><h4>${ARM_LABELS[a]} рука</h4><p class="muted">${esc(slot.arms[a].label)}${slot.arms[a].phase?` · ${esc(slot.arms[a].phase)}`:''}</p>${setsView(slot.plan[a])}</div>`).join('')}</div>
    ${details?`<div class="prog-actions">${!slot.attempts.length&&slot.status==='planned'?button('edit-slot','Изменить',`data-id="${slot.id}"`):''}${button('move','Перенести',`data-id="${slot.id}"`)}${slot.attempts.length?button('attempts','План и факт',`data-id="${slot.id}"`)+button('retry','Повторить занятие программы',`data-id="${slot.id}"`):''}${!slot.closed?button('skip','Пропустить',`data-id="${slot.id}"`):''}${slot.needsResolution?button('resolve-deletion','Оставить пропуск',`data-id="${slot.id}"`):''}</div>`:''}</article>`;
}
export function decisionsView(p) {
  return ARMS.filter(a=>p.arms[a]?.pending).map(a=>{
    const s=p.arms[a],c=p.config.arms[a],pending=s.pending,extra=`data-arm="${a}"`;
    let controls='';
    if(pending.type==='wave'||pending.type==='after-test') {
      const suggestion=waveSuggestion(s);
      controls=`<p>Силовая: ${suggestion.aOK?'три рабочих занятия подтверждены':'уровень пока не освоен'}. Объёмная: ${suggestion.bOK?'три рабочих занятия подтверждены':'уровень пока не освоен'}.</p>
      <div class="prog-fields">${['a','b'].map((d,i)=>`<label>${i?'Объёмная':'Силовая'} — следующий уровень<select id="decision-${a}-${d}">${[1,2,3,4].map(n=>`<option ${n===suggestion[d]?'selected':''}>${n}</option>`).join('')}</select></label>`).join('')}</div>
      ${suggestion.nextStage?`<label class="prog-check"><input id="stage-${a}" type="checkbox" checked>Перейти к этапу 2 с первого уровня</label>`:''}${button('decide-wave','Подтвердить следующую волну',extra,true)}${s.goalDone?button('finish-arm','Цель достигнута — закончить эту руку',extra):''}`;
    } else if(pending.type==='taper')controls=button('decide-taper','Назначить подводку и тест',extra,true)+button('decide-keep','Оставить разгрузку',extra);
    else if(pending.type==='retest')controls=`<label class="field">Вес нового теста<select id="retest-${a}">${options(s.pair,c.allowed)}</select></label>${button('decide-retest','Назначить новый тест',extra,true)}`;
    else {const next=nextPair(c,pairKey(s.pair));controls=`<p>${next?`Следующая пара: ${next.kg.toFixed(1)} кг · ${next.i}/${next.j}`:'Достигнута самая тяжёлая доступная пара.'}</p>${next?button('decide-increase','Повысить вес',extra,true):''}${button('decide-keep','Оставить текущий вес',extra)}`;}
    return `<div class="training-panel prog-decision"><h3>${ARM_LABELS[a]} · следующий шаг</h3><p>${esc(pending.reason)}</p><div class="prog-actions">${controls}</div></div>`;
  }).join('');
}
export function programView(p,active,all,workouts=[]) {
  const stats=progress(p),slot=currentSlot(p),last=p.slots.at(-1);
  const pain=p.slots.some(s=>s.evaluations&&Object.values(s.evaluations).some(e=>e.reason.startsWith('Боль:'))&&s.index>=Math.max(0,(slot?.index??p.slots.length)-1));
  const bestSix=arm=>workouts.filter(w=>w.progressionId===p.id&&w.feedback?.[arm]?.technique===true&&w.feedback?.[arm]?.pain===false).flatMap(w=>w.sets[arm]).filter(s=>s.status==='done'&&s.actualReps>=6&&!['invalid','assisted'].includes(s.quality)).sort((a,b)=>b.kg-a.kg||b.actualReps-a.actualReps)[0];
  return `<div class="training-heading prog-heading"><div><p class="eyebrow">ДВЕ РУКИ · СВОЙ ТЕМП</p><h1>${esc(p.name)}</h1><p class="training-lead">${status(p.status)} · ${slot?`Неделя ${slot.week} из ${Math.ceil(p.slots.length/2)}`:'Плановый период пройден'}</p></div></div>
    <label class="field">Мои программы<select id="programSelect">${all.map(x=>`<option value="${x.id}" ${p.id===x.id?'selected':''}>${esc(x.name)} · ${status(x.status)}</option>`).join('')}</select></label>
    <div class="training-panel prog-summary"><div class="prog-line"><strong>${stats.done} из ${stats.total} занятий</strong><span>${stats.percent}%</span></div><progress max="100" value="${stats.percent}" aria-label="Прохождение программы"></progress><p class="muted">Частичных: ${stats.partial} · пропущенных: ${stats.skipped} · план до ${esc(last?.date)}${p.config.horizon?` · ориентир ${p.config.horizon} недель`:''}</p>
    <div class="prog-arms prog-overview">${ARMS.filter(a=>p.arms[a]).map(a=>`<div><strong>${ARM_LABELS[a]}</strong><p>${METHODS[p.arms[a].method]}</p><small>${p.arms[a].method==='wave'?`Этап ${p.arms[a].stage} · волна ${p.arms[a].wave} · уровни А/Б ${p.arms[a].levelA}/${p.arms[a].levelB} · цель ${pairKey(p.config.arms[a].goal).kg} × 6`:`Блок ${p.arms[a].block} · ${pairKey(p.arms[a].pair).kg} кг`}${p.arms[a].goalDone?' · цель подтверждена':''}</small></div>`).join('')}</div></div>
    ${pain?`<div class="training-panel prog-decision"><h3>В прошлом занятии отмечена боль</h3><p>Прекрати тяжёлую работу при боли. Повышение не предлагается.</p>${button('pause','Пауза')}${button('future-settings','Пересмотреть назначения')}</div>`:''}
    ${p.needsExtension?`<div class="training-panel"><p>${esc(p.needsExtension.reason)} Предлагается +4 недели; продолжительность и процент будут пересчитаны.</p>${button('extend-wave','Добавить повторную волну')}${button('keep-period','Оставить период')}</div>`:''}
    ${p.slots.filter(s=>s.needsResolution).map(s=>`<div class="training-panel"><p>Удалена зачтённая запись недели ${s.week}. Более поздние занятия сохранены.</p>${button('retry','Повторить',`data-id="${s.id}"`)}${button('resolve-deletion','Оставить пропуск',`data-id="${s.id}"`)}</div>`).join('')}
    ${ARMS.some(a=>bestSix(a))?`<details class="training-panel"><summary>Подтверждённые результаты</summary>${ARMS.filter(a=>bestSix(a)).map(a=>`<p>${ARM_LABELS[a]}: ${bestSix(a).kg} кг × ${bestSix(a).actualReps}. Это достигнутый подход, не расчётный 6ПМ.</p>`).join('')}</details>`:''}
    ${decisionsView(p)}
    ${p.decisions.at(-1)?.type==='extend'?'<p class="training-message">Период продлён. Общее число занятий увеличилось, поэтому процент прохождения мог уменьшиться.</p>':''}
    ${active?`<div class="resume-card"><div><strong>Есть незавершённая тренировка</strong><small>${esc(active.title)}</small></div>${button('resume','Продолжить','',true)}</div>`:slot?`<div class="training-panel"><p class="eyebrow">СЛЕДУЮЩЕЕ ЗАНЯТИЕ</p>${slotView(slot)}<div class="prog-actions">${p.status==='active'&&!Object.values(p.arms).some(s=>s.pending)?button('start','Начать тренировку',`data-id="${slot.id}"`,true):''}${slot.status==='partial'?button('advance-partial','Продолжить программу без зачёта',`data-id="${slot.id}"`):''}</div></div>`:'<div class="training-panel"><h2>Период закончился</h2><p>Незавершённые блоки сохраняются. Можно продлить план или завершить программу.</p></div>'}
    <details class="training-panel"><summary>Вся программа · ${Math.ceil(p.slots.length/2)} недель</summary>${button('current','К текущей неделе')}${Array.from({length:Math.ceil(p.slots.length/8)},(_,i)=>`<details class="prog-wave" ${slot&&Math.floor(slot.index/8)===i?'open':''}><summary>Недели ${i*4+1}–${Math.min(i*4+4,Math.ceil(p.slots.length/2))}</summary>${p.slots.slice(i*8,i*8+8).map(s=>slotView(s,true)).join('')}</details>`).join('')}</details>
    <details class="training-panel"><summary>Управление программой</summary><div class="prog-actions">${['draft','paused'].includes(p.status)?button('activate',p.status==='draft'?'Запустить':'Продолжить'):''}${p.status==='active'?button('pause','Приостановить'):''}${button('future-settings','Будущие настройки')}${button('extend','Продлить период')}${button('history','История программы')}${button('finish','Завершить досрочно')}${button('archive','В архив')}${button('create','Новая прогрессия')}</div></details>
    <details class="training-panel"><summary>История решений · ${p.decisions.length}</summary>${p.decisions.length?p.decisions.map(d=>`<p>${esc(d.at?.slice(0,10))} · ${esc(d.arm?ARM_LABELS[d.arm]:'')} ${esc(d.pending?.reason||d.reason||d.type||'Изменение плана')} ${d.choice?`→ ${esc(d.choice.action)}`:''}</p>`).join(''):'<p>Изменений пока нет.</p>'}</details>`;
}
export function armForm(config,arm) {
  const c=config,a=ARM_LABELS[arm];
  const weights=[...new Set(Object.values(WAVE).flatMap(t=>[...t.a.flat(),...t.b.flat(),...t.deload.map(d=>d[0])]).concat([66.9,73.8,79.9,90.6,93.7]))].sort((a,b)=>a-b);
  return `<h2>${a} рука</h2><label class="field">Методика<select name="method" id="armMethod">${Object.entries(METHODS).map(([k,v])=>`<option value="${k}" ${c.method===k?'selected':''}>${v}</option>`).join('')}</select></label>
  <p class="muted">${c.method==='wave'?'Два направления нагрузки, три рабочие недели и разгрузка. Повышение по подтверждённым результатам.':c.method==='double'?'Набирай повторы в диапазоне. Когда верхняя граница достигнута во всех подходах — следующий вес.':'Тест N, затем 4×(N−2). По одному повторению за успешное занятие до 4×N. Недобор возвращает к началу блока.'}</p>
  <label class="field">${c.method==='ladder'?'Вес первого теста · ориентир из 10ПМ':'Исходная рабочая пара'}<select name="pair">${options(c.pair)}</select></label>
  ${c.method==='ladder'?`<p class="muted">${c.hasRecord10?'Предложен вес записи на 10 повторений этой руки.':'Записи на 10 повторений нет. Выбери доступный вес для теста самостоятельно.'}</p><label class="prog-check"><input name="pairConfirmed" type="checkbox" ${c.pairConfirmed?'checked':''} required>Подтверждаю вес первого теста</label>`:''}
  ${c.method==='double'?`<div class="prog-fields"><label>Подходы<input name="sets" type="number" min="1" max="20" value="${c.sets}" required></label><label>От повторов<input name="low" type="number" min="1" max="999" value="${c.low}" required></label><label>До повторов<input name="high" type="number" min="1" max="999" value="${c.high}" required></label></div>`:''}
  <label class="field">Отдых, секунд<input name="rest" type="number" min="0" max="3600" value="${c.rest}" required></label>
  ${c.method==='wave'?`<label class="field">Исходный 1ПМ, кг · ориентир<input name="base" type="number" min="1" step="0.1" value="${c.base}" required></label><label class="prog-check"><input name="baseConfirmed" type="checkbox" ${c.baseConfirmed?'checked':''} required>Подтверждаю показатель этой руки. Это не новая запись рекорда.</label>
  <details><summary>Исходная повторная работа · необязательно</summary><p>Сохраняется как ориентир, без пересчёта в «точный» 1ПМ.</p><label class="field">Пара<select name="referencePair"><option value="">Не указана</option>${options(c.referencePair||'')}</select></label><div class="prog-fields"><label>Подходы<input name="referenceSets" type="number" min="1" max="20" value="${c.referenceSets||''}"></label><label>Повторы<input name="referenceReps" type="number" min="1" max="999" value="${c.referenceReps||''}"></label></div></details>
  <div class="prog-fields"><label>Начальный уровень А<input name="initialA" type="number" min="1" max="4" value="${c.initialA}"></label><label>Начальный уровень Б<input name="initialB" type="number" min="1" max="4" value="${c.initialB}"></label><label>Отдых Б, с<input name="restB" type="number" min="0" max="3600" value="${c.restB}"></label><label>Разгрузка, с<input name="restDeload" type="number" min="0" max="3600" value="${c.restDeload}"></label></div>
  <label class="field">Цель · шесть закрытий<select name="goal">${options(c.goal)}</select></label><p class="muted">100 кг нет в каталоге: 99,4 кг ниже 100, 104,0 кг выше. Выбор пары определяет саму цель.</p>
  <label class="field">Готовность к тесту · шестёрка с запасом ≥1<select name="readiness">${options(c.readiness)}</select></label>
  <details><summary>Проверить и изменить лестницу весов</summary><p>Базовый профиль: 1ПМ около 100 кг, повторная работа около 67,8 кг 5×11. При другом профиле или цели пересмотри назначения. Вес не масштабируется автоматически.</p><div class="prog-fields">${weights.map(kg=>`<label>${kg} кг →<select name="override-${kg}">${options(c.overrides[String(kg)]||keyPair(PAIRS.find(p=>p.kg===kg)))}</select></label>`).join('')}</div></details>
  <label class="prog-check"><input name="reviewed" type="checkbox" ${c.reviewed?'checked':''} required>Проверил исходный профиль, лестницу, готовность и цель. Назначения подходят для этой руки.</label>`:''}
  <label class="field">Стандарт закрытия<textarea name="standard" maxlength="500">${esc(c.standard)}</textarea></label>
  <details><summary>Доступные пары · ${c.allowed.length} из ${PAIRS.length}</summary><p class="muted">Используются только отмеченные пары. Замены на более лёгкие будут показаны перед запуском.</p><div class="prog-pairs">${PAIRS.map(p=>`<label class="prog-check"><input name="allowed" type="checkbox" value="${keyPair(p)}" ${c.allowed.includes(keyPair(p))?'checked':''}>${p.kg} кг · ${p.i}/${p.j}</label>`).join('')}</div></details>`;
}
